# Root-level netlify.toml

[build]
  command = "echo 'Skipping app build; deploying Netlify Functions only'"
  publish = "."                       # Prevents Netlify Next.js plugin errors
  functions = "netlify/functions"
  environment = { NODE_VERSION = "20" }

[functions]
  node_bundler = "esbuild"
  included_files = ["src/data/disposable-domains.json"]

[[redirects]]
  from = "/api/validate-email"
  to = "/.netlify/functions/validate-email"
  status = 200
  force = true
