# Ensure the file is named netlify.toml (not netlify.toml or netlify.toml.txt)
# and is placed at the root of your repository.

[build]
  functions = "netlify/functions"
  environment = { NODE_VERSION = "20" }
  command = "echo 'Skipping app build; deploying Netlify Functions only'"

[functions]
  node_bundler = "esbuild"
  included_files = ["src/data/disposable-domains.json"]

[[redirects]]
  from = "/api/validate-email"
  to = "/.netlify/functions/validate-email"
  status = 200
  force = true
