[build]
  command = "echo 'Skipping app build; deploying Netlify Functions only'"
  functions = "netlify/functions"
  publish = "dist"  # Must be a separate folder from base directory
  environment = { NODE_VERSION = "20" }

[functions]
  node_bundler = "esbuild"
  included_files = ["src/data/disposable-domains.json"]

[[redirects]]
  from = "/api/validate-email"
  to = "/.netlify/functions/validate-email"
  status = 200
  force = true
[plugins]
  ignore = ["@netlify/plugin-nextjs"]